all:
	cd ./prep2;make;make install
	cd ./compile2;make;make install
	cd ./run2;make;make install
	cd ./main2;make;make install

clean:
	cd ./prep2;make clean;
	cd ./compile2;make clean;
	cd ./run2;make clean;
	cd ./main2;make clean;
	
