#ifndef _ACTION_NUMBER_H_INCLUDED_
#define _ACTION_NUMBER_H_INCLUDED_

#define ACTION_SUB_END	1
#define ACTION_SUB_BEGIN 2
#define ACTION_LABEL 3
#define ACTION_PUSH 4
#define ACTION_PUSARY 5
#define ACTION_SAV 6
#define ACTION_SAVARY 7
#define ACTION_CLEAR 8
#define ACTION_CALL 9
#define ACTION_GOTO 10
#define ACTION_GOTOFALSE 11
#define ACTION_ADD 12
#define ACTION_SUB 13
#define ACTION_MUL 14
#define ACTION_DIV 15
#define ACTION_LT 16
#define ACTION_GT 17
#define ACTION_GE 18
#define ACTION_LE 19
#define ACTION_EQ 20
#define ACTION_NE 21
#define ACTION_NOT 22
#define ACTION_SAVMAP 23
#define ACTION_PUSMAP 24
#define ACTION_MINUS 25



#endif
